# Generated by Django 5.1.4 on 2026-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("admission_date", models.DateField(auto_now_add=True)),
                ("parent_name", models.CharField(max_length=200)),
                ("parent_phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="students/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
