# Generated by Django 5.1.4 on 2026-07-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0001_initial"),
        ("students", "0002_student_classroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="parents.parent",
            ),
        ),
    ]
