# Generated by Django 5.1.4 on 2026-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="behavior",
            name="notes",
        ),
        migrations.AddField(
            model_name="behavior",
            name="teacher_notes",
            field=models.TextField(blank=True, verbose_name="Teacher Notes"),
        ),
    ]
