# Generated by Django 5.1.4 on 2026-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0002_remove_behavior_notes_behavior_teacher_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="behavior",
            name="ai_report",
            field=models.TextField(
                blank=True, editable=False, verbose_name="AI Progress Report"
            ),
        ),
    ]
