# Generated by Django 5.1.4 on 2026-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("qualification", models.CharField(max_length=200)),
                (
                    "experience",
                    models.PositiveIntegerField(help_text="Years of experience"),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="teachers/"),
                ),
                ("joining_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
